FROM openjdk:8-jdk-alpine3.9

RUN mkdir -p /home/java
COPY demo-0.0.1-SNAPSHOT.jar /home/java/
COPY start-java.sh /home/java/
RUN chmod -R 755 /home/java/start-java.sh

EXPOSE 8080
ENTRYPOINT ["/bin/sh","-c","/home/java/start-java.sh"]
